// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS87N43OYdMBydfkc3JvzeFq3N1U3v1x0',
    appId: '1:253212817159:web:a8d7b3faae2a7a879ef7a2',
    messagingSenderId: '253212817159',
    projectId: 'mbps-v1',
    authDomain: 'mbps-v1.firebaseapp.com',
    storageBucket: 'mbps-v1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQwIJIAFjzlrQGqMbLylbMj-NqO4I2xAo',
    appId: '1:253212817159:android:e0f0d0a1f52d95c39ef7a2',
    messagingSenderId: '253212817159',
    projectId: 'mbps-v1',
    storageBucket: 'mbps-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNBpt9FEtCxhDgj8-QM5uBAHQV3V-WQhM',
    appId: '1:253212817159:ios:6ff1e7b0c5908b699ef7a2',
    messagingSenderId: '253212817159',
    projectId: 'mbps-v1',
    storageBucket: 'mbps-v1.firebasestorage.app',
    iosBundleId: 'com.example.projectbps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNBpt9FEtCxhDgj8-QM5uBAHQV3V-WQhM',
    appId: '1:253212817159:ios:6ff1e7b0c5908b699ef7a2',
    messagingSenderId: '253212817159',
    projectId: 'mbps-v1',
    storageBucket: 'mbps-v1.firebasestorage.app',
    iosBundleId: 'com.example.projectbps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS87N43OYdMBydfkc3JvzeFq3N1U3v1x0',
    appId: '1:253212817159:web:32e2d48d1bd91da59ef7a2',
    messagingSenderId: '253212817159',
    projectId: 'mbps-v1',
    authDomain: 'mbps-v1.firebaseapp.com',
    storageBucket: 'mbps-v1.firebasestorage.app',
  );
}
